import type { Knex } from "knex";
export const config = { transaction: false };
/** Approved LENDING-DB-18 through LENDING-DB-32. */
export async function up(knex: Knex): Promise<void> {
  if (await knex.schema.hasTable("loan_automated_evaluations")) return;
  await knex.raw(`
  ALTER TABLE public.loan_applications ALTER COLUMN requested_amount TYPE bigint USING round(requested_amount*100)::bigint, ALTER COLUMN approved_amount TYPE bigint USING CASE WHEN approved_amount IS NULL THEN NULL ELSE round(approved_amount*100)::bigint END, ALTER COLUMN requested_interest_rate TYPE numeric(18,10), ALTER COLUMN approved_interest_rate TYPE numeric(18,10), ADD COLUMN currency char(3) NOT NULL DEFAULT 'NGN' CHECK(currency~'^[A-Z]{3}$'), ADD COLUMN idempotency_key varchar(255), ADD COLUMN request_hash char(64), ADD COLUMN correlation_id uuid, ADD COLUMN product_configuration_hash char(64), ADD COLUMN kyc_tier varchar(50), ADD COLUMN kyc_status varchar(30), ADD COLUMN kyc_verification_reference varchar(255), ADD COLUMN affordability_input_hash char(64), ADD COLUMN consent_reference varchar(255), ADD COLUMN evidence_observed_at timestamptz, ADD COLUMN evidence_expires_at timestamptz;
  ALTER TABLE public.loan_applications ADD CONSTRAINT uq_loan_application_tenant_id UNIQUE(tenant_id,id), ADD CONSTRAINT uq_loan_application_idempotency UNIQUE(tenant_id,idempotency_key), ADD CONSTRAINT fk_application_version_tenant FOREIGN KEY(tenant_id,loan_product_version_id) REFERENCES public.loan_product_versions(tenant_id,id), ADD CONSTRAINT chk_application_ngn CHECK(currency='NGN'), ADD CONSTRAINT chk_application_submission_evidence CHECK(status='DRAFT' OR (submitted_at IS NOT NULL AND loan_product_version_id IS NOT NULL AND product_configuration_hash IS NOT NULL AND idempotency_key IS NOT NULL AND request_hash IS NOT NULL AND consent_reference IS NOT NULL));
  ALTER TABLE public.loan_application_decisions ALTER COLUMN approved_amount TYPE bigint USING CASE WHEN approved_amount IS NULL THEN NULL ELSE round(approved_amount*100)::bigint END, ALTER COLUMN approved_interest_rate TYPE numeric(18,10), ADD COLUMN decision_source varchar(20) NOT NULL DEFAULT 'AUTOMATED' CHECK(decision_source IN('AUTOMATED','MANUAL')), ADD COLUMN policy_version varchar(100), ADD COLUMN model_version varchar(100), ADD COLUMN reason_codes jsonb NOT NULL DEFAULT '[]'::jsonb, ADD COLUMN evaluation_id uuid, ADD COLUMN request_hash char(64), ADD COLUMN approval_id uuid;
  ALTER TABLE public.loan_application_decisions ADD CONSTRAINT uq_application_decision_tenant_id UNIQUE(tenant_id,id), ADD CONSTRAINT fk_application_decision_tenant FOREIGN KEY(tenant_id,application_id) REFERENCES public.loan_applications(tenant_id,id);

  CREATE TABLE public.loan_automated_evaluations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,application_id uuid NOT NULL,policy_version varchar(100) NOT NULL,model_version varchar(100),product_configuration_hash char(64) NOT NULL,input_hash char(64) NOT NULL,rule_snapshot_hash char(64) NOT NULL,status varchar(30) NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','PROCESSING','COMPLETED','FAILED','DEAD_LETTERED')),outcome public.loan_decision_enum,score numeric(18,10),reason_codes jsonb NOT NULL DEFAULT '[]'::jsonb,idempotency_key varchar(255) NOT NULL,retry_count integer NOT NULL DEFAULT 0 CHECK(retry_count>=0),worker_id varchar(100),lease_expires_at timestamptz,last_error_code varchar(100),last_error text,created_at timestamptz NOT NULL DEFAULT now(),started_at timestamptz,completed_at timestamptz,UNIQUE(tenant_id,idempotency_key),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,application_id) REFERENCES public.loan_applications(tenant_id,id));
  CREATE TABLE public.loan_automated_rule_results(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,evaluation_id uuid NOT NULL,application_id uuid NOT NULL,rule_code varchar(100) NOT NULL,rule_version varchar(100) NOT NULL,outcome varchar(10) NOT NULL CHECK(outcome IN('PASS','FAIL','REFER')),reason_code varchar(100) NOT NULL,observed_value_hash char(64) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(evaluation_id,rule_code),FOREIGN KEY(tenant_id,evaluation_id) REFERENCES public.loan_automated_evaluations(tenant_id,id),FOREIGN KEY(tenant_id,application_id) REFERENCES public.loan_applications(tenant_id,id));
  ALTER TABLE public.loan_application_decisions ADD CONSTRAINT fk_decision_evaluation_tenant FOREIGN KEY(tenant_id,evaluation_id) REFERENCES public.loan_automated_evaluations(tenant_id,id);
  CREATE UNIQUE INDEX uq_final_automated_decision ON public.loan_application_decisions(tenant_id,evaluation_id) WHERE decision_source='AUTOMATED';
  CREATE INDEX idx_application_customer_history ON public.loan_applications(tenant_id,customer_id,created_at DESC);
  CREATE INDEX idx_evaluation_claim ON public.loan_automated_evaluations(status,lease_expires_at,created_at) WHERE status IN('PENDING','PROCESSING');
  CREATE INDEX idx_application_manual_review ON public.loan_applications(tenant_id,updated_at) WHERE status='UNDER_REVIEW';

  CREATE OR REPLACE FUNCTION public.validate_application_transition() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.status IS DISTINCT FROM OLD.status AND NOT((OLD.status='DRAFT' AND NEW.status='SUBMITTED') OR (OLD.status='SUBMITTED' AND NEW.status='ELIGIBILITY_CHECK') OR (OLD.status='ELIGIBILITY_CHECK' AND NEW.status IN('APPROVED','REJECTED','UNDER_REVIEW')) OR (OLD.status IN('SUBMITTED','ELIGIBILITY_CHECK','UNDER_REVIEW') AND NEW.status='CANCELLED')) THEN RAISE EXCEPTION 'Invalid loan application transition'; END IF; IF TG_OP='UPDATE' AND (NEW.tenant_id,NEW.customer_id,NEW.loan_product_id,NEW.loan_product_version_id,NEW.requested_amount,NEW.requested_tenure_days,NEW.currency,NEW.idempotency_key,NEW.request_hash,NEW.product_configuration_hash,NEW.consent_reference) IS DISTINCT FROM (OLD.tenant_id,OLD.customer_id,OLD.loan_product_id,OLD.loan_product_version_id,OLD.requested_amount,OLD.requested_tenure_days,OLD.currency,OLD.idempotency_key,OLD.request_hash,OLD.product_configuration_hash,OLD.consent_reference) THEN RAISE EXCEPTION 'Application submission evidence is immutable'; END IF; RETURN NEW; END $$;
  CREATE TRIGGER trg_validate_application_transition BEFORE UPDATE ON public.loan_applications FOR EACH ROW EXECUTE FUNCTION public.validate_application_transition();
  CREATE OR REPLACE FUNCTION public.record_application_status() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='INSERT' OR NEW.status IS DISTINCT FROM OLD.status THEN INSERT INTO public.loan_application_events(tenant_id,application_id,event_type,previous_status,new_status,event_data) VALUES(NEW.tenant_id,NEW.id,'STATUS_CHANGED',CASE WHEN TG_OP='INSERT' THEN NULL ELSE OLD.status END,NEW.status,'{}'); END IF; RETURN NEW; END $$;
  CREATE TRIGGER trg_record_application_status AFTER INSERT OR UPDATE OF status ON public.loan_applications FOR EACH ROW EXECUTE FUNCTION public.record_application_status();
  CREATE OR REPLACE FUNCTION public.protect_underwriting_evidence() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Underwriting evidence is immutable'; END $$;
  CREATE TRIGGER trg_protect_rule_result BEFORE UPDATE OR DELETE ON public.loan_automated_rule_results FOR EACH ROW EXECUTE FUNCTION public.protect_underwriting_evidence();
  CREATE TRIGGER trg_protect_decision BEFORE UPDATE OR DELETE ON public.loan_application_decisions FOR EACH ROW EXECUTE FUNCTION public.protect_underwriting_evidence();
  CREATE OR REPLACE FUNCTION public.protect_completed_evaluation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='DELETE' OR OLD.status IN('COMPLETED','DEAD_LETTERED') THEN RAISE EXCEPTION 'Completed underwriting evaluation is immutable'; END IF; RETURN NEW; END $$;
  CREATE TRIGGER trg_protect_completed_evaluation BEFORE UPDATE OR DELETE ON public.loan_automated_evaluations FOR EACH ROW EXECUTE FUNCTION public.protect_completed_evaluation();
  CREATE OR REPLACE FUNCTION public.protect_application_events() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Application lifecycle history is immutable'; END $$;
  CREATE TRIGGER trg_protect_application_events BEFORE UPDATE OR DELETE ON public.loan_application_events FOR EACH ROW EXECUTE FUNCTION public.protect_application_events();

  ALTER TABLE public.loan_automated_evaluations ENABLE ROW LEVEL SECURITY;ALTER TABLE public.loan_automated_evaluations FORCE ROW LEVEL SECURITY;ALTER TABLE public.loan_automated_rule_results ENABLE ROW LEVEL SECURITY;ALTER TABLE public.loan_automated_rule_results FORCE ROW LEVEL SECURITY;
  CREATE POLICY automated_evaluation_tenant_policy ON public.loan_automated_evaluations USING(tenant_id=public.current_tenant_uuid()) WITH CHECK(tenant_id=public.current_tenant_uuid());CREATE POLICY automated_rule_result_tenant_policy ON public.loan_automated_rule_results USING(tenant_id=public.current_tenant_uuid()) WITH CHECK(tenant_id=public.current_tenant_uuid());
  GRANT SELECT,INSERT,UPDATE ON public.loan_automated_evaluations TO parc_lending_runtime,parc_lending_worker;GRANT SELECT,INSERT ON public.loan_automated_rule_results TO parc_lending_runtime,parc_lending_worker;
`);
}
export function down(): Promise<never> {
  return Promise.reject(
    new Error("LN-02 underwriting controls are forward-only"),
  );
}
